server:
  port: 8567
  servlet:
    context-path: /api

spring:
  application:
    name: ai-content-creation
  profiles:
    active: local
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
    redis:
      namespace: content:user:prefix
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_content_creation
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
  ai:
    dashscope:
      api-key: ${dashscope.api-key}
    article-title-agent-model:
      api-key: ${dashscope.api-key}
      model: qwen-turbo
      max-tokens: 8124
    article-content-agent-model:
      api-key: ${dashscope.api-key}
      model: qwen-max
    image-generate-model:
      api-key: ${dashscope.api-key}
      model: qwen-plus

pexels:
  api-key: ${pexels.api-key}

# nano-banana AI图片生成
nano-banana:
  api-key: ${nano-banana.api-key}
  model: gemini-3-pro-image-preview

# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: ${cos.host}
    secretId: ${cos.secretId}
    secretKey: ${cos.secretKey}
    region: ${cos.region}
    bucket: ${cos.bucket}


# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.caoerlin.aicontentcreation.controller
# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.mapper
  type-aliases-package: com.caoerlin.aicontentcreation.model.dto.user
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的字段名
      logic-delete-field: is_delete
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0